### ISSUE TITLE
How to list all jobs in queue?

### ISSUE THREAD

**Issue by giaur500** [samderlust/async_queue#2]
Assuming there's some remaining jobs in the queue, I am able to get job count, by calling `size` getter. I'm missing remaining jobs info though. Is it possible to list all queued jobs in the queue to show them to user? Also, every job should have some kind of description.

So, my proposal:
- add parameter `descrription` to `addJob` method, or generic field to make possible to put my own object there
- add method/getter to return iterable containing every job info from queue, with objects that have been added as described above

What do you think? BTW, what happens with failed jobs when retry count reaches value set when adding? Will they by removed from queue or I am able to retry them again?

**Comment by giaur500** [comment]
`when the job reaches its max retry time, it will be removed from the queue. I think I will need to add an event to emit that a job reaches its limit of retry and still failed`

I think good idea is to be able to retry failed jobs manually even if limit has been reached. Simplest way is reset their limit counters, so they will be executed again as configured, or emit event so i will able to cache them and add to queue again.

Currently, is there any way to be aware failed jobs with limit reached have been removed? Or need to add that feature (event for that)? In my case, it's required to be sure there won't be any lost jobs, even failed.

**Comment by samderlust** [comment]
@giaur500  Currently there is no event emitted when a job reaches its retry limit. In your case, I think you can do a recursive call in `try catch` or when the result is failed.
for ex:

```
  Future<void> doSomething() async {
    //actual job
  }

  asyncQ.addJob(() async {
    try {
      await doSomething();
    } catch (e) {
      await doSomething();
    }
  });

  ```

**Comment by samderlust** [comment]
@giaur500 Currently there is no event emitted when a job reaches its retry limit. In your case, I think you can do a recursive call in try catch or when the result is failed.
for ex:
```

  Future<void> doRecursiveJob() async {
    try {
      ///do somthing
    } catch (e) {
      await doRecursiveJob();
    }
  }

  asyncQ.addJob(doRecursiveJob);

```

Hope this help

**Comment by giaur500** [comment]
Thanks for suggrstion, I will also look when you add that feature. Do you avcept PR if I decide to add it by myself?

**Comment by samderlust** [comment]
@giaur500 hi, I'll try to add the feature tonight, after work.

I'll let you know how it goes.

Every contribution is well come!

**Comment by samderlust** [comment]
@giaur500  Hi, 
I've just published version 1.3. Thanks for your suggestion. Here is the change log:
```
- option to add `label` and `description` when adding job
- [label] need to be unique unless [DuplicatedLabelException] will throw.
- in [AsyncQueue.addJob] if provide `retryTime = -1` will make the job retry infinitely until it success. You still have to explicitly call `retry`. Be careful when using this option.
- emit event when job hits its max retry limit [QueueEventType.retryLimitReached]
- add [AsyncQueue.list] and [AsyncQueue.getJobInfo] to retrieve the jobs info event when queue finished
- add [AsyncQueue.clear] to clear the info list and also stop the queue if it's running
```

**Comment by samderlust** [comment]
```
      final q = AsyncQueue();
      q.addJob(() => Future.delayed(mil100, () {}));
      q.addJob(() => Future.delayed(mil100, q.retry), label: "retryJob");
      q.addJob(() => Future.delayed(mil100, () {}));

      await q.start();
      print(q.list());
      
```
this code will print:
```
[JobInfo(label: 2022-11-10T21:51:40.247578, description: null, state: JobState.done, retryCount: 0, maxRetry: 1)
, JobInfo(label: retryJob, description: null, state: JobState.failed, retryCount: 1, maxRetry: 1)
, JobInfo(label: 2022-11-10T21:51:40.248858, description: null, state: JobState.done, retryCount: 0, maxRetry: 1)
]
```

**Comment by giaur500** [comment]
Excellent! Other question - is it possible to get initial future from failed job? It looks like `JobInfo` class does not include it. So I am able to get failed job description only, but that's not possible to add it back to queue again?
Perhaps it would be good idea to a add `Job` object to `JobInfo` and `QueueEvent` classes to make possible to get any particular job in form exactly how it's been added? Then, failed jobs could be added again to queue with the same settings to let them to be executed again with configured retry count.

Currently, I can get info some job is failed, but I have no enough info to do something with that and also I won't get enough info to setup that job again to add to queue. I guess I need to store that info outside the queue.

**Comment by samderlust** [comment]
@giaur500 
I was thinking about that. But then I realized it could break the fundamental of the queue when exposing the `Job`  object. 
For example, someone will call the `job` to execute while the queue is running in its natural flow, `first come, first serve`.

So what I'm thinking is, to allow users to re-add the job `at the end` of the queue only. 
But I don't know if that use case would work when you have a queue of job and 1 job need to run successfully in order for the next job to run. 

What do you think?

**Comment by giaur500** [comment]
Isn't that assumed all jobs in queue are independent? But I think re-add job at the end of queue is fine. 

Or, make possible to re-create job to add it to queue as new job, for the same task. To make it possible, we can expose future from any particular job or instead string label field, allow to add any object, so I will able to save all required info.

But still, string label is still not enough in any case, I think it would be better to have `AsyncQueue<T>` and allow to put any object instead string label. So in listener, there will be full finished/failed job info available. 

Btw, is there any way to get job result in listener? For example, I got event some job is finished or failed  Can I get job result also? For example, rest api call - can I pass result from particular job and get result in queue listener? After rest api call (or any other future), I will get event job is finished, but how to access result to do something with it?

**Comment by samderlust** [comment]
@giaur500  my initial though when writing this package is that to run a job one after the other. and users are able to stop the whole queue if one of them failed.

`But still, string label is still not enough in any case, I think it would be better to have AsyncQueue<T> and allow to put any object instead string label. So in listener, there will be full finished/failed job info available.`

AsyncQueue<T> may not be useful, cuz  as you said, all jobs are dependent, Type return by this job may not be the same as the other one. `AsyncQueue` just make sure that async job is run in order

I thinks i can make `AsyncQueue` add a `Object extra` into a Job Node. But could you please elaborate on the use case for this?


`Btw, is there any way to get job result in listener? For example, I got event some job is finished or failed Can I get job result also? For example, rest api call - can I pass result from particular job and get result in queue listener? After rest api call (or any other future), I will get event job is finished, but how to access result to do something with it?`

I never think of this, but  i think you can achieve this by declaring a global variable and assign it to the result in `job 1`. Then in other jobs, you can act base on what that global variable is.

**Comment by giaur500** [comment]
> I never think of this, but i think you can achieve this by declaring a global variable and assign it to the result in job 1. Then in other jobs, you can act base on what that global variable is.
> Type return by this job may not be the same as the other one. AsyncQueue just make sure that async job is run in order

That's true. So, maybe good idea to pass return values to listner as dynamic field? Event type `after job` can include dynamic field with return value from particular job related to event. User needs to know what is return type, because event should also include job details.

> I thinks i can make AsyncQueue add a Object extra into a Job Node. But could you please elaborate on the use case for this?

The problem with string field is that I'm not able to pass more complex job info to listener. Thus, I'm not able to show what's been executed exactly. Also, not possible to pass all info needed to re-create failed job and add it to queue again if required.  Maybe all jobs should notify gui directly, but queue has listener, so better to use listener to get all events from queue.

> my initial though when writing this package is that to run a job one after the other. and users are able to stop the whole queue if one of them failed

Why stop whole queue if any job failed? Failed job should be removed from queue (and, listener should get event failed job details and reason, like exception message returned from job) and next job should be run (failed means tries limit exceeded). By saying `jobs are independent` I mean return value from previous job is not required by next job to run.

**Comment by samderlust** [comment]
@giaur500 

I've just published a new branch  that exposes the `AsyncNode`
https://pub.dev/packages/async_queue/versions/2.0.0-dev.1

Please give it a try and see what need to improve

**Comment by giaur500** [comment]
Hi,

Sorry for delay, I had no time to respond. Can you provide some sample how to re-add failed job? Also, can you decrease target sdk version? I am forced to use older Flutter version (sdk 2.16) and it seems I can't override it when plugin has 2.18.
